    //array of lesson objects
    lessons = [{
        id: 0,
        title: "Maths",
        location: "London",
        price: 150,
        spaces: 5,
        image: "math.png"
    }, {
        id: 1,
        title: "English",
        location: "Oxford",
        price: 100,
        spaces: 5,
        image: "eng.png"
    }, {
        id: 2,
        title: "Physics",
        location: "Manchester",
        price: 200,
        spaces: 5,
        image: "phy.png"
    }, {
        id: 3,
        title: "Chemistry",
        location: "Bristol",
        price: 120,
        spaces: 5,
        image: "chem.png"
    }, {
        id: 4,
        title: "Biology",
        location: "Brighton",
        price: 200,
        spaces: 5,
        image: "bio.png"
    }, {
        id: 5,
        title: "Football",
        location: "Edinburgh",
        price: 180,
        spaces: 5,
        image: "foot.png"
    }, {
        id: 6,
        title: "Guitar",
        location: "London",
        price: 300,
        spaces: 5,
        image: "guitar.png"
    }, {
        id: 7,
        title: "Piano",
        location: "Portsmouth",
        price: 400,
        spaces: 5,
        image: "piano.png"
    }, {
        id: 8,
        title: "Cricket",
        location: "Liverpool",
        price: 180,
        spaces: 5,
        image: "cric.png"
    }, {
        id: 9,
        title: "IT",
        location: "Blackburn",
        price: 250,
        spaces: 5,
        image: "it.png"
    }]